### PR TITLE
Fix test for manage api

### PR DESCRIPTION
**Pull request by marla-singer**
### Changes
1. common.js
   - Add navigation to Catalog
   - Change condition for main page
2. testfiles/testdocument.json
   - Edit json file to valid swagger documentation
3. manage api
   - Move a recurring part in section "beforeEach"
   - Add comments
   - Change order run
   - Change xpath to css selector

Ready for review

### CODE REVIEW

**Comment by jykae** [comment]
@marla-singer Is this ready for review?

**Comment by marla-singer** [comment]
@jykae Yes, it is

**Comment by jykae** [comment]
🆒 I review

**Comment by jykae** [comment]
@marla-singer I get this, but I try to check if it's some error with my chromedriver

```
1) Manage API Backend "before all" hook:
     SessionNotCreatedError: session not created exception
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":326577,660350}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
```

**Comment by marla-singer** [comment]
@jykae What chrome version do you have? If it's 54, you should update your chrome driver to 2.25 version. I faced with it too the few hours ago
http://chromedriver.storage.googleapis.com/index.html?path=2.25/

**Comment by jykae** [comment]
@marla-singer didn't help :/

```
1) Manage API Backend "before all" hook:
     SessionNotCreatedError: session not created exception
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":327184,278327}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.0 x86_64)
```

**Comment by marla-singer** [comment]
@jykae um. Reboot PC? I don't know :hushed: It's okay from my side

**Comment by jykae** [comment]
@marla-singer Weird... now it runs but reaaally sloow 😩 

```
 Manage API Backend
    1) "before each" hook for "10.1 should view api backend details"
    2) "after each" hook for "10.1 should view api backend details"
    3) "after all" hook


  0 passing (3m)
  3 failing

  1) Manage API Backend "before each" hook for "10.1 should view api backend details":
     Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test.


  2) Manage API Backend "after each" hook for "10.1 should view api backend details":
     Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test.


  3) Manage API Backend "after all" hook:
     Error: timeout of 60000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by marla-singer** [comment]
@jykae What?! O_o Why it is so?

**Comment by jykae** [comment]
Rebooted, same sessionError again, maybe @brylie could try out if this runs, I try to figure out what's wrong with my driver.

**Comment by brylie** [comment]
All ten tests passed for me in 2 minutes.

screenshot_20161026_155644

**Comment by marla-singer** [comment]
@brylie It makes me happy

**Comment by jykae** [comment]
Found my issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1552&can=1&q=session%20osx&colspec=ID%20Status%20Pri%20Owner%20Summary

works great @marla-singer

**Pull request merged**
