### PR TITLE
Hotfix/registration

### PR DESCRIPTION
**Pull request by 55**
Registation test fixes
Work in progress…

### CODE REVIEW

**Comment by marla-singer** [comment]
@nnn I'm going to fix test for login and there are the same. Maybe I can complete your work in this file?

**Comment by jykae** [comment]
@marla-singer I think you can assign yourself on this. 
ping @bajiat

**Comment by 55** [comment]
@marla-singer thanks!

**Comment by jykae** [comment]
@marla-singer how is work on this proceeding?

**Comment by marla-singer** [comment]
@jykae It takes more time that I think. I have problem with 1.3 point. Still fight with it

**Comment by jykae** [comment]
@marla-singer ok, let me know if I can help

**Comment by jykae** [comment]
PR #12 replaced this one & got merged. Closing.

**Pull request closed without merging**
